### ISSUE TITLE
Limit ncpus/threads?

### ISSUE THREAD

**Issue by dthorburn** [umarov90/DeepRAG#1]
Hi, 

I'm trying to use your tool but the job on the university HPC keeps getting killed for what appears to be too many threads being spawned. For context, I am using a conda environment with python 3.6 and TF 1.7.0. The jobs get 1 node, 32 cpus, and 62GB of memory. 

Here is the code ```python predict.py -I $DATA_DIR/Reference_Genome.fasta -O $OUT_DIR/${Chrom}_regulatory_regions.gff -C ${Chrom}```

And here is the error:
```
2021-11-04 14:32:58.974553: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
=>> PBS: job killed: ncpus 142.68 exceeded limit 32 (sum)
```

Is there a way to limit the number of threads the ```predict.py``` script will spawn (assuming this is actually the issue)?

Thanks in advance for your time.

EDIT: I am having different issues with getting the GPU drivers working on the HPC, so as it currently stands I can only use the CPU version.

**Comment by umarov90** [comment]
Hello,

The script itself does not spawn any additional threads. So the threads are probably spawned by TensorFlow itself. Can you try setting intra_op_parallelism_threads as described here:
https://stackoverflow.com/questions/34389945/changing-the-number-of-threads-in-tensorflow-on-cifar10
There are three places in predict.py which you will need to change (188, 227, 272).

Hope this helps!

**Comment by umarov90** [comment]
Another relevant question/answer:
https://stackoverflow.com/questions/49677913/keras-tensorflow-limit-number-of-cores-intra-op-parallelism-threads-not-wor

**Comment by dthorburn** [comment]
Thanks for the quick response. Limiting the number of threads on the lines you suggested seems to have worked and it is now running.
